package workflow

import (
	"os"
	"testing"
	"time"
)

// TestShimAnswersMatchTheInstalledSchema checks the shape of what the shim
// sends against the schema the installed Codex produces.
//
// It is a separate case from the scenario on purpose. The scenario needs the
// shim, not Codex, so a machine without Codex still runs it in full; only this
// check skips, and says why. See schema_test.go for what shape does and does
// not prove.
func TestShimAnswersMatchTheInstalledSchema(t *testing.T) {
	binary := enterScenario(t, "shim-answers-match-schema")

	c := Start(t, Spec{
		Name:    "shim-answers-match-schema",
		Harness: "codex",
		Observations: []string{
			"the installed schema is available",
			"the initialize reply matches InitializeResponse",
			"the thread/start reply matches ThreadStartResponse",
			"the conversation object matches Thread",
		},
		Deadline: 120 * time.Second,
	})
	iso := Isolate(t, c, binary)

	c.Note("generating the schema from the installed codex")
	bundle, why := loadSchema(c, iso.Home)
	if bundle == nil {
		// Unsupported, not skipped silently and not passed: the capability is
		// absent, the case says so by name, and the scenario is unaffected.
		for _, observation := range c.spec.Observations {
			c.Unsupported(observation, why)
		}
		return
	}
	c.Observed("the installed schema is available", "generated by the installed codex")

	peer := &shimPeer{}
	initialize, err := peer.initialize([]byte(`{"clientInfo":{"name":"rewake-shim","version":"0.0.1"},"capabilities":{"experimentalApi":true}}`))
	if err != nil {
		c.Contradicted("the initialize reply matches InitializeResponse", "the shim refused a valid initialize: %v", err)
		return
	}
	check(c, bundle, "InitializeResponse", "the initialize reply matches InitializeResponse", initialize)

	session := &shimSession{thread: shimThread}
	reply, _, err := session.answer(peer, "thread/start",
		[]byte(`{"threadSource":"user","config":{},"runtimeWorkspaceRoots":["/work"]}`))
	if err != nil {
		c.Contradicted("the thread/start reply matches ThreadStartResponse", "the shim refused a valid start: %v", err)
		c.Contradicted("the conversation object matches Thread", "there was no reply to read a conversation from")
		return
	}
	check(c, bundle, "ThreadStartResponse", "the thread/start reply matches ThreadStartResponse", reply)

	message, err := asMessage(reply)
	if err != nil {
		c.Contradicted("the conversation object matches Thread", "unreadable reply: %v", err)
		return
	}
	check(c, bundle, "Thread", "the conversation object matches Thread", message["thread"])
}

// check records one observation from a schema comparison.
func check(c *Case, bundle *schemaBundle, typeName, observation string, value any) {
	message, err := asMessage(value)
	if err != nil {
		c.Contradicted(observation, "unreadable %s: %v", typeName, err)
		return
	}
	if problems := bundle.check(typeName, message); len(problems) > 0 {
		c.Contradicted(observation, "%s", describe(problems))
		return
	}
	c.Observed(observation, "matches "+typeName)
}

// The schema check needs a HOME to write into; Isolate provides one, and this
// keeps the generated 4 MB inside the case so it goes away with it.
var _ = os.Getenv
