package internal

// The harness words rule 2 found on its first run over the 1.x tree, file by
// file, each with the step that takes it out (docs/v2/stage3-packages.md) and
// the count and sum of the mentions it excuses (excuse). A mention added, removed
// or replaced fails until the entry says so, and an entry with none left fails,
// so the table only shrinks as the steps land.

// Why a mention is still there.
const (
	codexLeaves              = "Codex leaves the tree (answer 5), and its ids, transports, fixtures and comments with it"
	serverLeaves             = "bridge/server, the MCP server, leaves with Codex"
	acceptLeaves             = "accept serves only a Codex resume and leaves with it (correction 5)"
	claudeInjectionLeaves    = "the Claude Code MCP injection and its transport leave"
	hooksLeave               = "Claude Code's hook machinery, its telemetry and the grant keeper leave"
	ticketsOnATransport      = "the ticket keys on a harness's transport; S7 puts it on a neutral transport with its turn-id declaration"
	channelCarriesTheHarness = "the channel record carries the harness; S8 removes the field and the MCP letters"
	realAdapterIDs           = "a test or a comment takes a real adapter's id; from S10 the catalog value and the fixture supply it"
	harnessWordsInTexts      = "a help or role text names a harness; from S10 the harness words come from the adapter"
	harnessDirectories       = "the harness directories come from each adapter's ProtectedDirs from S10"
	explainsByOneHarness     = "a comment explains core code by one harness's behavior; reworded when the tables empty"
)

var nameExceptions = map[nameException]excuse{
	{"internal/alias/alias.go", "claude"}:                         {realAdapterIDs, "S10", 1, "f9f563e31055"},
	{"internal/alias/alias.go", "codex"}:                          {codexLeaves, "S8", 3, "d7ec6f08d1d9"},
	{"internal/alias/alias_file_test.go", "codex"}:                {codexLeaves, "S8", 16, "0e7028b9f764"},
	{"internal/alias/alias_file_test.go", "claude"}:               {realAdapterIDs, "S10", 4, "a990b0d5e755"},
	{"internal/alias/alias_test.go", "codex"}:                     {codexLeaves, "S8", 62, "e0baf47c0c09"},
	{"internal/alias/command_test.go", "claude"}:                  {realAdapterIDs, "S10", 16, "fe2bd2c5b3b6"},
	{"internal/alias/command_test.go", "codex"}:                   {codexLeaves, "S8", 4, "22d4a5f69741"},
	{"internal/alias/harness_flags_test.go", "claude"}:            {realAdapterIDs, "S10", 2, "020a62d6b459"},
	{"internal/alias/harness_flags_test.go", "codex"}:             {codexLeaves, "S8", 1, "b04066323601"},
	{"internal/bridge/bridge.go", "codex"}:                        {codexLeaves, "S8", 4, "2a4374a4764a"},
	{"internal/bridge/bridge.go", "claude"}:                       {claudeInjectionLeaves, "S8", 2, "303de3b7f224"},
	{"internal/bridge/endpoint/bind_test.go", "codex"}:            {codexLeaves, "S8", 21, "35bb1bab6325"},
	{"internal/bridge/endpoint/bind_test.go", "claude"}:           {hooksLeave, "S9", 5, "764755e26aeb"},
	{"internal/bridge/endpoint/calls.go", "codex"}:                {codexLeaves, "S8", 9, "f194a400c411"},
	{"internal/bridge/endpoint/calls.go", "claude"}:               {hooksLeave, "S9", 5, "b7444a11b018"},
	{"internal/bridge/endpoint/channel.go", "codex"}:              {codexLeaves, "S8", 3, "3e1a3d5982b2"},
	{"internal/bridge/endpoint/channel_order_test.go", "codex"}:   {codexLeaves, "S8", 4, "b81cb17be74e"},
	{"internal/bridge/endpoint/channel_test.go", "codex"}:         {codexLeaves, "S8", 9, "0c0bdeb9e7c5"},
	{"internal/bridge/endpoint/channel_test.go", "claude"}:        {hooksLeave, "S9", 2, "a1d60ff04231"},
	{"internal/bridge/endpoint/client.go", "claude"}:              {claudeInjectionLeaves, "S8", 2, "a597367f95c1"},
	{"internal/bridge/endpoint/config.go", "claude"}:              {hooksLeave, "S9", 3, "739723509bbe"},
	{"internal/bridge/endpoint/events.go", "claude"}:              {hooksLeave, "S9", 7, "f5d8aa335167"},
	{"internal/bridge/endpoint/events.go", "mcp__"}:               {hooksLeave, "S9", 1, "aff126afa440"},
	{"internal/bridge/endpoint/events.go", "codex"}:               {codexLeaves, "S8", 6, "1fdd983cd201"},
	{"internal/bridge/endpoint/events_test.go", "codex"}:          {codexLeaves, "S8", 35, "42d58446c2af"},
	{"internal/bridge/endpoint/events_test.go", "claude"}:         {hooksLeave, "S9", 11, "98d090f3cd9f"},
	{"internal/bridge/endpoint/events_test.go", "mcp__"}:          {hooksLeave, "S9", 3, "e83bc9956297"},
	{"internal/bridge/endpoint/hello_test.go", "codex"}:           {ticketsOnATransport, "S7", 9, "81a86532c6f5"},
	{"internal/bridge/endpoint/helpers_test.go", "codex"}:         {codexLeaves, "S8", 10, "28bbbd88becc"},
	{"internal/bridge/endpoint/limits.go", "claude"}:              {hooksLeave, "S9", 5, "2608d95548d8"},
	{"internal/bridge/endpoint/limits_test.go", "claude"}:         {hooksLeave, "S9", 2, "7e5b524031fe"},
	{"internal/bridge/endpoint/order_table_test.go", "codex"}:     {ticketsOnATransport, "S7", 6, "f602d2225436"},
	{"internal/bridge/endpoint/protocol.go", "claude"}:            {hooksLeave, "S9", 1, "1089d4d6d524"},
	{"internal/bridge/endpoint/protocol.go", "codex"}:             {codexLeaves, "S8", 1, "1089d4d6d524"},
	{"internal/bridge/endpoint/tickets_end_test.go", "codex"}:     {ticketsOnATransport, "S7", 27, "dd9d9f096578"},
	{"internal/bridge/endpoint/tickets_end_test.go", "claude"}:    {hooksLeave, "S9", 4, "2552c2f3e33c"},
	{"internal/bridge/endpoint/tickets_end_test.go", "mcp__"}:     {hooksLeave, "S9", 1, "66776d034851"},
	{"internal/bridge/endpoint/tickets_test.go", "codex"}:         {ticketsOnATransport, "S7", 56, "5b311cbd9019"},
	{"internal/bridge/endpoint/tickets_test.go", "claude"}:        {ticketsOnATransport, "S7", 6, "28de6138c63c"},
	{"internal/bridge/server/child_bound_test.go", "codex"}:       {serverLeaves, "S8", 2, "07453687996f"},
	{"internal/bridge/server/evidence_test.go", "codex"}:          {serverLeaves, "S8", 7, "d8a78071f155"},
	{"internal/bridge/server/fault_test.go", "codex"}:             {serverLeaves, "S8", 3, "e4f5a055f3c0"},
	{"internal/bridge/server/fault_variants_test.go", "codex"}:    {serverLeaves, "S8", 1, "4afe5c2b025b"},
	{"internal/bridge/server/flow_test.go", "codex"}:              {serverLeaves, "S8", 8, "7ac16bc0a08c"},
	{"internal/bridge/server/flow_test.go", "claude"}:             {serverLeaves, "S8", 7, "1be4a160a8bb"},
	{"internal/bridge/server/mcp_test.go", "codex"}:               {serverLeaves, "S8", 5, "ca43e74ea1f8"},
	{"internal/bridge/server/order_call_test.go", "codex"}:        {serverLeaves, "S8", 3, "4f620eca403b"},
	{"internal/bridge/server/order_cut_test.go", "codex"}:         {serverLeaves, "S8", 2, "07453687996f"},
	{"internal/bridge/server/order_gen_test.go", "codex"}:         {serverLeaves, "S8", 1, "4afe5c2b025b"},
	{"internal/bridge/server/order_marks_test.go", "codex"}:       {serverLeaves, "S8", 2, "07453687996f"},
	{"internal/bridge/server/order_test.go", "codex"}:             {serverLeaves, "S8", 2, "07453687996f"},
	{"internal/bridge/server/rig_test.go", "codex"}:               {serverLeaves, "S8", 17, "6371f171008e"},
	{"internal/bridge/server/rig_test.go", "mcp__"}:               {serverLeaves, "S8", 1, "aff126afa440"},
	{"internal/bridge/server/rig_test.go", "claude"}:              {serverLeaves, "S8", 1, "66f478872196"},
	{"internal/bridge/server/server.go", "codex"}:                 {serverLeaves, "S8", 10, "46e9c1afe0f2"},
	{"internal/bridge/server/server.go", "claude"}:                {serverLeaves, "S8", 6, "42cf372950f1"},
	{"internal/bridge/server/stdout_bound_test.go", "codex"}:      {serverLeaves, "S8", 4, "3e9adb440c74"},
	{"internal/channel/connections_test.go", "codex"}:             {channelCarriesTheHarness, "S8", 4, "8149e4db6e73"},
	{"internal/channel/connections_test.go", "claude"}:            {channelCarriesTheHarness, "S8", 1, "29bc7c514426"},
	{"internal/channel/events.go", "codex"}:                       {channelCarriesTheHarness, "S8", 8, "8087c1986abd"},
	{"internal/channel/events.go", "claude"}:                      {channelCarriesTheHarness, "S8", 3, "d73d7102822f"},
	{"internal/channel/history.go", "codex"}:                      {channelCarriesTheHarness, "S8", 15, "319890ce2aa9"},
	{"internal/channel/history.go", "claude"}:                     {channelCarriesTheHarness, "S8", 7, "c16f8ef1b659"},
	{"internal/channel/late_test.go", "codex"}:                    {channelCarriesTheHarness, "S8", 3, "bb79dc21fdc2"},
	{"internal/channel/late_test.go", "claude"}:                   {channelCarriesTheHarness, "S8", 2, "a98b93c99c4d"},
	{"internal/channel/notices.go", "claude"}:                     {channelCarriesTheHarness, "S8", 2, "377c6a8cb469"},
	{"internal/channel/notices_test.go", "codex"}:                 {channelCarriesTheHarness, "S8", 2, "f05b7226e9bf"},
	{"internal/channel/notices_test.go", "claude"}:                {channelCarriesTheHarness, "S8", 1, "29bc7c514426"},
	{"internal/channel/order_test.go", "codex"}:                   {channelCarriesTheHarness, "S8", 1, "32d31dd97b30"},
	{"internal/channel/order_test.go", "claude"}:                  {channelCarriesTheHarness, "S8", 1, "29bc7c514426"},
	{"internal/channel/record.go", "codex"}:                       {channelCarriesTheHarness, "S8", 3, "17e4ecf3ae80"},
	{"internal/channel/record.go", "claude"}:                      {channelCarriesTheHarness, "S8", 2, "413d3c83721f"},
	{"internal/channel/selection.go", "codex"}:                    {channelCarriesTheHarness, "S8", 6, "10fe75100351"},
	{"internal/channel/selection.go", "claude"}:                   {channelCarriesTheHarness, "S8", 1, "edf76db7403b"},
	{"internal/channel/selection_oracle_test.go", "codex"}:        {channelCarriesTheHarness, "S8", 1, "f81889d4f11f"},
	{"internal/channel/selection_space_test.go", "codex"}:         {channelCarriesTheHarness, "S8", 4, "36f62c88c879"},
	{"internal/channel/space_oracle_test.go", "claude"}:           {channelCarriesTheHarness, "S8", 2, "775023417f27"},
	{"internal/channel/space_oracle_test.go", "codex"}:            {channelCarriesTheHarness, "S8", 1, "32d31dd97b30"},
	{"internal/channel/space_test.go", "codex"}:                   {channelCarriesTheHarness, "S8", 3, "6c169a7798b5"},
	{"internal/channel/space_test.go", "claude"}:                  {channelCarriesTheHarness, "S8", 3, "7074b7c8770b"},
	{"internal/channel/table_codex_test.go", "codex"}:             {channelCarriesTheHarness, "S8", 49, "1c6a3f8541a1"},
	{"internal/channel/table_codex_test.go", "claude"}:            {channelCarriesTheHarness, "S8", 6, "0856b834e375"},
	{"internal/channel/table_test.go", "codex"}:                   {channelCarriesTheHarness, "S8", 17, "7502de4e2b41"},
	{"internal/channel/table_test.go", "claude"}:                  {channelCarriesTheHarness, "S8", 10, "9d75f9c1d020"},
	{"internal/cli/accept.go", "codex"}:                           {acceptLeaves, "S8", 3, "e10f5577c29d"},
	{"internal/cli/accept_test.go", "codex"}:                      {acceptLeaves, "S8", 6, "a8ab4bc057f6"},
	{"internal/cli/accept_test.go", "claude"}:                     {acceptLeaves, "S8", 1, "0bac7c392141"},
	{"internal/cli/args.go", "claude"}:                            {harnessWordsInTexts, "S10", 2, "ae90d4831642"},
	{"internal/cli/bridge_tool_test.go", "codex"}:                 {ticketsOnATransport, "S7", 1, "4afe5c2b025b"},
	{"internal/cli/bridge_tool_test.go", "claude"}:                {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/channel_display_test.go", "claude"}:            {realAdapterIDs, "S10", 3, "2b3e014abd12"},
	{"internal/cli/channel_display_test.go", "codex"}:             {codexLeaves, "S8", 1, "32d31dd97b30"},
	{"internal/cli/cli_test.go", "claude"}:                        {realAdapterIDs, "S10", 4, "c2d29210c047"},
	{"internal/cli/cli_test.go", "codex"}:                         {codexLeaves, "S8", 1, "b04066323601"},
	{"internal/cli/command_flag_test.go", "claude"}:               {realAdapterIDs, "S10", 6, "1cb6709ff94e"},
	{"internal/cli/command_flag_test.go", "codex"}:                {codexLeaves, "S8", 6, "81d0f23eb4e4"},
	{"internal/cli/edit_grant_test.go", "codex"}:                  {codexLeaves, "S8", 1, "b04066323601"},
	{"internal/cli/error_report_test.go", "codex"}:                {codexLeaves, "S8", 3, "8e45c8316fef"},
	{"internal/cli/gateway_integration_test.go", "app-server"}:    {codexLeaves, "S8", 1, "a2f0eae6b1bc"},
	{"internal/cli/gateway_intent_test.go", "codex"}:              {codexLeaves, "S8", 1, "0ec343a8933f"},
	{"internal/cli/general_test.go", "codex"}:                     {codexLeaves, "S8", 2, "6c79572c4405"},
	{"internal/cli/granthook.go", "claude"}:                       {hooksLeave, "S9", 3, "13ceeca52feb"},
	{"internal/cli/granthook_test.go", "claude"}:                  {hooksLeave, "S9", 3, "b8952a69c5c1"},
	{"internal/cli/inbox_owed.go", "codex"}:                       {codexLeaves, "S8", 1, "937fb123862d"},
	{"internal/cli/inbox_parts.go", "claude"}:                     {claudeInjectionLeaves, "S8", 2, "292d2f7998a1"},
	{"internal/cli/inbox_test.go", "codex"}:                       {codexLeaves, "S8", 1, "9e22f2cd1e53"},
	{"internal/cli/journal_test.go", "codex"}:                     {ticketsOnATransport, "S7", 1, "4afe5c2b025b"},
	{"internal/cli/launch.go", "claude"}:                          {harnessWordsInTexts, "S10", 1, "48cb0b1e954c"},
	{"internal/cli/launch.go", "codex"}:                           {codexLeaves, "S8", 2, "fb1c557fa900"},
	{"internal/cli/launch_nested_test.go", "claude"}:              {realAdapterIDs, "S10", 1, "546748e7e9b9"},
	{"internal/cli/launch_worktree_test.go", "codex"}:             {codexLeaves, "S8", 16, "21cbc57cb4b6"},
	{"internal/cli/launch_worktree_test.go", "claude"}:            {realAdapterIDs, "S10", 10, "913edbc3847f"},
	{"internal/cli/model.go", "claude"}:                           {harnessWordsInTexts, "S10", 1, "b65954e036ba"},
	{"internal/cli/pending.go", "claude"}:                         {hooksLeave, "S9", 6, "435d5d5a56c5"},
	{"internal/cli/pending_test.go", "codex"}:                     {codexLeaves, "S8", 1, "e195bedc56d9"},
	{"internal/cli/pending_test.go", "claude"}:                    {hooksLeave, "S9", 1, "18f2ef1f656b"},
	{"internal/cli/pending_turn.go", "codex"}:                     {ticketsOnATransport, "S7", 2, "07453687996f"},
	{"internal/cli/pending_turn.go", "claude"}:                    {ticketsOnATransport, "S7", 1, "ff2353177870"},
	{"internal/cli/read_test.go", "claude"}:                       {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/registry.go", "claude"}:                        {harnessWordsInTexts, "S10", 11, "059ca837ca41"},
	{"internal/cli/registry.go", "codex"}:                         {codexLeaves, "S8", 4, "6c756ffc57f8"},
	{"internal/cli/registry.go", "app-server"}:                    {codexLeaves, "S8", 1, "2ff96b58573f"},
	{"internal/cli/registry_internal.go", "claude"}:               {hooksLeave, "S9", 7, "42cb2c894490"},
	{"internal/cli/registry_send.go", "claude"}:                   {harnessWordsInTexts, "S10", 5, "8a9a63488cf4"},
	{"internal/cli/registry_send.go", "codex"}:                    {codexLeaves, "S8", 9, "20e85f71b82c"},
	{"internal/cli/registry_send.go", ".agents"}:                  {harnessDirectories, "S10", 2, "aafb2f3b47c7"},
	{"internal/cli/role_test.go", "claude"}:                       {realAdapterIDs, "S10", 2, "fac1f46fa9dd"},
	{"internal/cli/role_test.go", "codex"}:                        {codexLeaves, "S8", 3, "04c0572d28b4"},
	{"internal/cli/rooms_test.go", "claude"}:                      {realAdapterIDs, "S10", 3, "9472489bb6cd"},
	{"internal/cli/rooms_test.go", "codex"}:                       {codexLeaves, "S8", 1, "b04066323601"},
	{"internal/cli/send_dir_test.go", "codex"}:                    {codexLeaves, "S8", 12, "7fe1ebc46052"},
	{"internal/cli/send_dir_test.go", "claude"}:                   {hooksLeave, "S9", 4, "47cfbef27805"},
	{"internal/cli/send_git.go", "codex"}:                         {codexLeaves, "S8", 3, "380ac24b08d0"},
	{"internal/cli/send_git_test.go", "codex"}:                    {codexLeaves, "S8", 2, "56de8c892a62"},
	{"internal/cli/send_git_test.go", "claude"}:                   {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/send_grant_test.go", "codex"}:                  {codexLeaves, "S8", 8, "6a8e7eee4dba"},
	{"internal/cli/session_state.go", "codex"}:                    {codexLeaves, "S8", 1, "25784c8b1d5f"},
	{"internal/cli/sessions.go", "claude"}:                        {harnessWordsInTexts, "S10", 1, "e9424ee9757f"},
	{"internal/cli/sessions_test.go", "claude"}:                   {realAdapterIDs, "S10", 2, "29fc6a495088"},
	{"internal/cli/shell_channel_test.go", "claude"}:              {realAdapterIDs, "S10", 3, "2b3e014abd12"},
	{"internal/cli/steer.go", "claude"}:                           {explainsByOneHarness, "S19", 1, "88a93d4a5671"},
	{"internal/cli/steer_test.go", "claude"}:                      {realAdapterIDs, "S10", 12, "5df1c51c652e"},
	{"internal/cli/steer_test.go", "codex"}:                       {codexLeaves, "S8", 8, "4792cede5343"},
	{"internal/cli/telemetry.go", "claude"}:                       {hooksLeave, "S9", 4, "472cd9aa2827"},
	{"internal/cli/thread_claude_test.go", "claude"}:              {hooksLeave, "S9", 2, "978a609688c8"},
	{"internal/cli/thread_claude_test.go", "codex"}:               {codexLeaves, "S8", 1, "c05e2fc2d22b"},
	{"internal/cli/thread_report_test.go", "codex"}:               {codexLeaves, "S8", 2, "780ec8f20a4f"},
	{"internal/cli/thread_report_test.go", "claude"}:              {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/turn_hold.go", "claude"}:                       {hooksLeave, "S9", 2, "183d0c091fff"},
	{"internal/cli/turn_hold_test.go", "claude"}:                  {hooksLeave, "S9", 2, "9d721dfe444f"},
	{"internal/cli/turn_hold_test.go", "codex"}:                   {codexLeaves, "S8", 2, "7b7ee77e845a"},
	{"internal/cli/turn_payload.go", "claude"}:                    {hooksLeave, "S9", 2, "64c0801cfd62"},
	{"internal/cli/turn_payload.go", "codex"}:                     {codexLeaves, "S8", 1, "2d77c484e23c"},
	{"internal/cli/turnended.go", "claude"}:                       {hooksLeave, "S9", 2, "e0b1304d60bd"},
	{"internal/cli/turnended.go", "codex"}:                        {codexLeaves, "S8", 2, "857154dc0f61"},
	{"internal/cli/worktree.go", "codex"}:                         {codexLeaves, "S8", 1, "b7770d0fa77d"},
	{"internal/cli/worktree.go", "claude"}:                        {harnessWordsInTexts, "S10", 1, "3528dfe7e8ef"},
	{"internal/cli/worktree_keep_test.go", "codex"}:               {codexLeaves, "S8", 5, "3cf5cc03ca27"},
	{"internal/cli/worktree_land_test.go", "codex"}:               {codexLeaves, "S8", 6, "e8c44d154c52"},
	{"internal/cli/worktree_test.go", "codex"}:                    {codexLeaves, "S8", 12, "1bf7c63efc73"},
	{"internal/control/control.go", "claude"}:                     {hooksLeave, "S9", 2, "5def4ce18653"},
	{"internal/control/control.go", "codex"}:                      {codexLeaves, "S8", 2, "0d13ef3ce3ec"},
	{"internal/control/serve.go", "app-server"}:                   {codexLeaves, "S8", 1, "27cb4a8481b6"},
	{"internal/control/serve.go", "codex"}:                        {codexLeaves, "S8", 1, "27cb4a8481b6"},
	{"internal/control/serve.go", "claude"}:                       {explainsByOneHarness, "S19", 1, "35666bd41899"},
	{"internal/grant/journal.go", "claude"}:                       {hooksLeave, "S9", 1, "b6ff45dd1a1b"},
	{"internal/grant/journal_sweep_test.go", "codex"}:             {codexLeaves, "S8", 1, "b04066323601"},
	{"internal/grant/rules.go", "claude"}:                         {harnessDirectories, "S10", 2, "ba6bf582fdd9"},
	{"internal/grant/rules.go", "codex"}:                          {codexLeaves, "S8", 1, "e419ea01416c"},
	{"internal/grant/rules.go", ".agents"}:                        {harnessDirectories, "S10", 1, "00264a0b6a6f"},
	{"internal/grant/rules_live_test.go", "claude"}:               {harnessDirectories, "S10", 3, "dd0e56719628"},
	{"internal/grant/rules_live_test.go", "codex"}:                {codexLeaves, "S8", 2, "35b6ad601a67"},
	{"internal/grant/rules_live_test.go", ".agents"}:              {harnessDirectories, "S10", 2, "4e727ba3f5fd"},
	{"internal/grant/rules_shield_test.go", "claude"}:             {harnessDirectories, "S10", 1, "02a9ffad5a79"},
	{"internal/grant/rules_shield_test.go", "codex"}:              {codexLeaves, "S8", 1, "39aa401b2200"},
	{"internal/grant/rules_shield_test.go", ".agents"}:            {harnessDirectories, "S10", 1, "dff5d33d1653"},
	{"internal/grant/rules_test.go", "codex"}:                     {codexLeaves, "S8", 3, "813ea8ad3b91"},
	{"internal/grant/rules_test.go", "claude"}:                    {harnessDirectories, "S10", 1, "3771568a0f25"},
	{"internal/grant/tiers.go", "codex"}:                          {codexLeaves, "S8", 1, "0ab7df15722a"},
	{"internal/grantauth/grantauth.go", "codex"}:                  {codexLeaves, "S8", 1, "f5ad174e4482"},
	{"internal/grantauth/helper_test.go", "codex"}:                {codexLeaves, "S8", 1, "51601c602ee4"},
	{"internal/grantauth/keeper.go", "claude"}:                    {hooksLeave, "S9", 3, "98c52af423cf"},
	{"internal/inbox/held.go", "claude"}:                          {explainsByOneHarness, "S19", 1, "6a12b71af3f5"},
	{"internal/inbox/inbox.go", "claude"}:                         {explainsByOneHarness, "S19", 1, "bea54e1d93a2"},
	{"internal/inbox/inbox.go", "codex"}:                          {codexLeaves, "S8", 2, "2a14c707e76c"},
	{"internal/inbox/inbox_test.go", "codex"}:                     {codexLeaves, "S8", 2, "51f4284f5747"},
	{"internal/inbox/journal_ends.go", "claude"}:                  {hooksLeave, "S9", 1, "2a81e610ed64"},
	{"internal/inbox/kept.go", "claude"}:                          {hooksLeave, "S9", 2, "f960bb0192e3"},
	{"internal/inbox/serve.go", "codex"}:                          {codexLeaves, "S8", 1, "677976088db1"},
	{"internal/inbox/window.go", "claude"}:                        {explainsByOneHarness, "S19", 1, "faa4320befd2"},
	{"internal/inbox/withdraw_test.go", "codex"}:                  {codexLeaves, "S8", 1, "b04066323601"},
	{"internal/proc/proc.go", "codex"}:                            {codexLeaves, "S8", 1, "c21b928e7a49"},
	{"internal/receipt/receipt_test.go", "codex"}:                 {codexLeaves, "S8", 1, "66585bf0af02"},
	{"internal/registry/hardening_test.go", "codex"}:              {codexLeaves, "S8", 1, "e9f551ad35cd"},
	{"internal/registry/liveness.go", "codex"}:                    {codexLeaves, "S8", 1, "a9b6f98f7013"},
	{"internal/registry/registry.go", "codex"}:                    {codexLeaves, "S8", 4, "563851dc68e6"},
	{"internal/registry/registry.go", "claude"}:                   {realAdapterIDs, "S10", 1, "1a2c9b51bcc7"},
	{"internal/registry/registry_test.go", "claude"}:              {realAdapterIDs, "S10", 9, "d46487a4c52c"},
	{"internal/role/playbook.go", "claude"}:                       {harnessWordsInTexts, "S10", 2, "b93213da4cec"},
	{"internal/role/playbook.go", "codex"}:                        {codexLeaves, "S8", 1, "f425282c3664"},
	{"internal/role/playbook_main.go", "codex"}:                   {codexLeaves, "S8", 5, "6db73d6f5512"},
	{"internal/role/playbook_main.go", ".agents"}:                 {harnessDirectories, "S10", 1, "b2f9a613fdd8"},
	{"internal/role/playbook_main.go", "claude"}:                  {harnessWordsInTexts, "S10", 4, "85a18f8c3860"},
	{"internal/role/role.go", "claude"}:                           {harnessWordsInTexts, "S10", 1, "5f7caa79426b"},
	{"internal/role/role.go", "codex"}:                            {codexLeaves, "S8", 1, "5f7caa79426b"},
	{"internal/state/paths.go", "claude"}:                         {hooksLeave, "S9", 2, "2bf97393ad2b"},
	{"internal/state/state.go", "codex"}:                          {codexLeaves, "S8", 2, "effa51a0da43"},
	{"internal/state/state_test.go", "claude"}:                    {realAdapterIDs, "S10", 1, "964b30cc6fc0"},
	{"internal/worktree/include.go", "claude"}:                    {explainsByOneHarness, "S19", 3, "a005ba09a070"},
	{"internal/worktree/include_rules.go", "claude"}:              {explainsByOneHarness, "S19", 1, "e5bfbb825bd0"},
	{"internal/worktree/name.go", "claude"}:                       {explainsByOneHarness, "S19", 2, "3a201afd2d72"},
	{"internal/worktree/worktree.go", "codex"}:                    {codexLeaves, "S8", 1, "bcd3e6a474ba"},
	{"internal/worktree/worktree_test.go", "codex"}:               {codexLeaves, "S8", 5, "5942dd05217b"},
	{"internal/wrap/channel_order_test.go", "codex"}:              {codexLeaves, "S8", 1, "32d31dd97b30"},
	{"internal/wrap/channel_test.go", "codex"}:                    {codexLeaves, "S8", 3, "4bf9bdd81639"},
	{"internal/wrap/compaction_letters.go", "claude"}:             {explainsByOneHarness, "S19", 2, "4827558520b0"},
	{"internal/wrap/compaction_letters.go", "codex"}:              {codexLeaves, "S8", 1, "fb8ad86148fe"},
	{"internal/wrap/compaction_letters_running_test.go", "codex"}: {codexLeaves, "S8", 1, "944cf24f9ef4"},
	{"internal/wrap/grant_resume_test.go", "claude"}:              {realAdapterIDs, "S10", 3, "a5d7dfc03ea9"},
	{"internal/wrap/grants.go", "codex"}:                          {codexLeaves, "S8", 1, "40255167902d"},
	{"internal/wrap/mailtool.go", "codex"}:                        {codexLeaves, "S8", 5, "99514f52503b"},
	{"internal/wrap/mailtool.go", "claude"}:                       {claudeInjectionLeaves, "S8", 2, "b69cf8f1eba5"},
	{"internal/wrap/mailtool_launch_test.go", "claude"}:           {claudeInjectionLeaves, "S8", 6, "1d5a841dc998"},
	{"internal/wrap/mailtool_version_test.go", "codex"}:           {codexLeaves, "S8", 3, "04c0572d28b4"},
	{"internal/wrap/ownership_test.go", "claude"}:                 {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/wrap/thread_test.go", "claude"}:                    {realAdapterIDs, "S10", 2, "4da672537616"},
	{"internal/wrap/wrap.go", "codex"}:                            {codexLeaves, "S8", 3, "6346411df7d2"},
	{"internal/wrap/wrap_test.go", "claude"}:                      {realAdapterIDs, "S10", 1, "f714ce850ec4"},
}
