package internal

// The harness words rule 2 found on its first run over the 1.x tree, file by
// file, each with the step that takes it out (docs/v2/stage3-packages.md) and
// the count and sum of the mentions it excuses (excuse). A mention added, removed
// or replaced fails until the entry says so, and an entry with none left fails,
// so the table only shrinks as the steps land.

// Why a mention is still there.
const (
	hooksLeave           = "Claude Code's hook machinery, its telemetry and the grant keeper leave"
	realAdapterIDs       = "a test or a comment takes a real adapter's id; from S10 the catalog value and the fixture supply it"
	harnessWordsInTexts  = "a help or role text names a harness; from S10 the harness words come from the adapter"
	harnessDirectories   = "the harness directories come from each adapter's ProtectedDirs from S10"
	explainsByOneHarness = "a comment explains core code by one harness's behavior; reworded when the tables empty"
)

var nameExceptions = map[nameException]excuse{
	{"internal/alias/alias_file_test.go", "claude"}:            {realAdapterIDs, "S10", 4, "891ee9c9c865"},
	{"internal/alias/command_test.go", "claude"}:               {realAdapterIDs, "S10", 16, "fe2bd2c5b3b6"},
	{"internal/alias/harness_flags_test.go", "claude"}:         {realAdapterIDs, "S10", 1, "e0f23a0152d7"},
	{"internal/bridge/bridge.go", "claude"}:                    {hooksLeave, "S9", 2, "303de3b7f224"},
	{"internal/bridge/endpoint/calls.go", "claude"}:            {hooksLeave, "S9", 4, "5c8e1dfe4b8c"},
	{"internal/bridge/endpoint/config.go", "claude"}:           {hooksLeave, "S9", 3, "739723509bbe"},
	{"internal/bridge/endpoint/events.go", "claude"}:           {hooksLeave, "S9", 6, "82c9986653a4"},
	{"internal/bridge/endpoint/events.go", "mcp__"}:            {hooksLeave, "S9", 1, "aff126afa440"},
	{"internal/bridge/endpoint/events_test.go", "claude"}:      {hooksLeave, "S9", 11, "98d090f3cd9f"},
	{"internal/bridge/endpoint/events_test.go", "mcp__"}:       {hooksLeave, "S9", 3, "e83bc9956297"},
	{"internal/bridge/endpoint/limits.go", "claude"}:           {hooksLeave, "S9", 4, "2d44c8058950"},
	{"internal/bridge/endpoint/limits_test.go", "claude"}:      {hooksLeave, "S9", 2, "c06bce6a8f22"},
	{"internal/bridge/endpoint/protocol.go", "claude"}:         {hooksLeave, "S9", 1, "d2761befd43f"},
	{"internal/bridge/endpoint/tickets_end_test.go", "claude"}: {hooksLeave, "S9", 4, "2552c2f3e33c"},
	{"internal/bridge/endpoint/tickets_end_test.go", "mcp__"}:  {hooksLeave, "S9", 1, "66776d034851"},
	{"internal/cli/args.go", "claude"}:                         {harnessWordsInTexts, "S10", 2, "ae90d4831642"},
	{"internal/cli/bridge_tool_test.go", "claude"}:             {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/cli_test.go", "claude"}:                     {realAdapterIDs, "S10", 4, "c2d29210c047"},
	{"internal/cli/command_flag_test.go", "claude"}:            {realAdapterIDs, "S10", 6, "1cb6709ff94e"},
	{"internal/cli/granthook.go", "claude"}:                    {hooksLeave, "S9", 3, "13ceeca52feb"},
	{"internal/cli/granthook_test.go", "claude"}:               {hooksLeave, "S9", 3, "b8952a69c5c1"},
	{"internal/cli/inbox_parts.go", "claude"}:                  {hooksLeave, "S9", 2, "292d2f7998a1"},
	{"internal/cli/launch.go", "claude"}:                       {harnessWordsInTexts, "S10", 1, "48cb0b1e954c"},
	{"internal/cli/launch_nested_test.go", "claude"}:           {realAdapterIDs, "S10", 1, "546748e7e9b9"},
	{"internal/cli/launch_worktree_test.go", "claude"}:         {realAdapterIDs, "S10", 10, "913edbc3847f"},
	{"internal/cli/model.go", "claude"}:                        {harnessWordsInTexts, "S10", 1, "b65954e036ba"},
	{"internal/cli/pending.go", "claude"}:                      {hooksLeave, "S9", 6, "435d5d5a56c5"},
	{"internal/cli/pending_test.go", "claude"}:                 {hooksLeave, "S9", 1, "18f2ef1f656b"},
	{"internal/cli/read_test.go", "claude"}:                    {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/registry.go", "claude"}:                     {harnessWordsInTexts, "S10", 11, "6d4d4d20d1c8"},
	{"internal/cli/registry_internal.go", "claude"}:            {hooksLeave, "S9", 5, "eb7990c17562"},
	{"internal/cli/registry_send.go", ".codex"}:                {harnessDirectories, "S10", 2, "aafb2f3b47c7"},
	{"internal/cli/registry_send.go", "claude"}:                {harnessWordsInTexts, "S10", 5, "f17443fa069f"},
	{"internal/cli/registry_send.go", ".agents"}:               {harnessDirectories, "S10", 2, "aafb2f3b47c7"},
	{"internal/cli/role_test.go", "claude"}:                    {realAdapterIDs, "S10", 2, "fac1f46fa9dd"},
	{"internal/cli/rooms_test.go", "claude"}:                   {realAdapterIDs, "S10", 3, "9472489bb6cd"},
	{"internal/cli/send_dir_test.go", "claude"}:                {hooksLeave, "S9", 4, "0dc2c0c5f2e9"},
	{"internal/cli/sessions.go", "claude"}:                     {harnessWordsInTexts, "S10", 1, "e9424ee9757f"},
	{"internal/cli/sessions_test.go", "claude"}:                {realAdapterIDs, "S10", 2, "29fc6a495088"},
	{"internal/cli/steer.go", "claude"}:                        {explainsByOneHarness, "S19", 1, "88a93d4a5671"},
	{"internal/cli/steer_test.go", "claude"}:                   {realAdapterIDs, "S10", 3, "f034a576dfed"},
	{"internal/cli/telemetry.go", "claude"}:                    {hooksLeave, "S9", 4, "472cd9aa2827"},
	{"internal/cli/thread_claude_test.go", "claude"}:           {hooksLeave, "S9", 2, "978a609688c8"},
	{"internal/cli/thread_report_test.go", "claude"}:           {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/cli/turn_hold.go", "claude"}:                    {hooksLeave, "S9", 2, "183d0c091fff"},
	{"internal/cli/turn_hold_test.go", "claude"}:               {hooksLeave, "S9", 2, "9d721dfe444f"},
	{"internal/cli/turn_payload.go", "claude"}:                 {hooksLeave, "S9", 1, "0d61f86d51c7"},
	{"internal/cli/turnended.go", "claude"}:                    {hooksLeave, "S9", 2, "e0b1304d60bd"},
	{"internal/cli/worktree.go", "claude"}:                     {harnessWordsInTexts, "S10", 1, "3528dfe7e8ef"},
	{"internal/control/control.go", "claude"}:                  {hooksLeave, "S9", 2, "ff732d28b978"},
	{"internal/control/serve.go", "claude"}:                    {explainsByOneHarness, "S19", 1, "35666bd41899"},
	{"internal/grant/journal.go", "claude"}:                    {hooksLeave, "S9", 1, "b6ff45dd1a1b"},
	{"internal/grant/rules.go", ".codex"}:                      {harnessDirectories, "S10", 1, "e419ea01416c"},
	{"internal/grant/rules.go", "claude"}:                      {harnessDirectories, "S10", 2, "ba6bf582fdd9"},
	{"internal/grant/rules.go", ".agents"}:                     {harnessDirectories, "S10", 1, "00264a0b6a6f"},
	{"internal/grant/rules_live_test.go", ".codex"}:            {harnessDirectories, "S10", 2, "35b6ad601a67"},
	{"internal/grant/rules_live_test.go", "claude"}:            {harnessDirectories, "S10", 3, "dd0e56719628"},
	{"internal/grant/rules_live_test.go", ".agents"}:           {harnessDirectories, "S10", 2, "4e727ba3f5fd"},
	{"internal/grant/rules_shield_test.go", ".codex"}:          {harnessDirectories, "S10", 1, "39aa401b2200"},
	{"internal/grant/rules_shield_test.go", "claude"}:          {harnessDirectories, "S10", 1, "02a9ffad5a79"},
	{"internal/grant/rules_shield_test.go", ".agents"}:         {harnessDirectories, "S10", 1, "dff5d33d1653"},
	{"internal/grant/rules_test.go", "claude"}:                 {harnessDirectories, "S10", 1, "3771568a0f25"},
	{"internal/grantauth/keeper.go", "claude"}:                 {hooksLeave, "S9", 3, "98c52af423cf"},
	{"internal/inbox/held.go", "claude"}:                       {explainsByOneHarness, "S19", 1, "6a12b71af3f5"},
	{"internal/inbox/inbox.go", "claude"}:                      {explainsByOneHarness, "S19", 1, "5d592dd0c53c"},
	{"internal/inbox/journal_ends.go", "claude"}:               {hooksLeave, "S9", 1, "2a81e610ed64"},
	{"internal/inbox/kept.go", "claude"}:                       {hooksLeave, "S9", 2, "f960bb0192e3"},
	{"internal/inbox/window.go", "claude"}:                     {explainsByOneHarness, "S19", 1, "faa4320befd2"},
	{"internal/registry/registry.go", "claude"}:                {realAdapterIDs, "S10", 1, "1a2c9b51bcc7"},
	{"internal/registry/registry_test.go", "claude"}:           {realAdapterIDs, "S10", 9, "d46487a4c52c"},
	{"internal/role/playbook.go", "claude"}:                    {harnessWordsInTexts, "S10", 2, "f198628550e8"},
	{"internal/role/playbook_main.go", ".codex"}:               {harnessDirectories, "S10", 1, "b2f9a613fdd8"},
	{"internal/role/playbook_main.go", ".agents"}:              {harnessDirectories, "S10", 1, "b2f9a613fdd8"},
	{"internal/role/playbook_main.go", "claude"}:               {harnessWordsInTexts, "S10", 4, "36bf7325b73f"},
	{"internal/role/role.go", "claude"}:                        {harnessWordsInTexts, "S10", 1, "6897abe791d9"},
	{"internal/state/paths.go", "claude"}:                      {hooksLeave, "S9", 2, "2bf97393ad2b"},
	{"internal/state/state_test.go", "claude"}:                 {realAdapterIDs, "S10", 1, "964b30cc6fc0"},
	{"internal/worktree/include.go", "claude"}:                 {explainsByOneHarness, "S19", 3, "a005ba09a070"},
	{"internal/worktree/include_rules.go", "claude"}:           {explainsByOneHarness, "S19", 1, "e5bfbb825bd0"},
	{"internal/worktree/name.go", "claude"}:                    {explainsByOneHarness, "S19", 2, "3a201afd2d72"},
	{"internal/wrap/compaction_letters.go", "claude"}:          {explainsByOneHarness, "S19", 2, "aea5ab33947f"},
	{"internal/wrap/grant_resume_test.go", "claude"}:           {realAdapterIDs, "S10", 3, "a5d7dfc03ea9"},
	{"internal/wrap/ownership_test.go", "claude"}:              {realAdapterIDs, "S10", 1, "0bac7c392141"},
	{"internal/wrap/thread_test.go", "claude"}:                 {realAdapterIDs, "S10", 2, "4da672537616"},
	{"internal/wrap/wrap_test.go", "claude"}:                   {realAdapterIDs, "S10", 1, "f714ce850ec4"},
}
